### PR TITLE
Add bundler compatibility

### PR DESCRIPTION
**Pull request by PierreRambaud**
Hi,

I'm one of these guys who don't use ChefDk because I have many cookbooks on my computer and not all of them are compatible with latest ChefDk :)
So, for this reason, I add a `Gemfile`, and edit `Rakefile` to allow `bundle` commands more I do a little change to call `destroy_machines` instead of having a duplicate command.

Regards,

### CODE REVIEW

**Comment by jjasghar** [comment]
I'm torn on this. Officially we're moving away from anything other than ChefDK, but for more people and adoption it makes sense.

@kramvan1 I know he has some opinions about this, I think this would be a good topic for discussion at one of our meetings.

@PierreRambaud any chance you can attend an IRC/Hangout and we can discuss it? 

All in all this doesn't look bad at all. Hell it's unabstrusive enough so we default to chefdk, but the Gemfile is there incase you need it.

Can you also update the PR to remove the note about the Gemfile in the readme too? We'll end up having to remove it if we merge this.

**Comment by PierreRambaud** [comment]
I update the PR as you requested.
I would be happy to discuss with you on IRC, I'm connected on the nickname `PierreRambaud` in **#openstack-chef** and **#chef** and will be there in approximately four hours.

**Comment by kramvan1** [comment]
Since this suite is focus solely on the openstack cookbooks, I would like to keep it clear of outside gem issues that a Gemfile would introduce.  Installing and using the ChefDK is simple and isolated, it should not effect other rubys you have installed.

If at some point we find the need to deviate from the gem provided by ChefDK, then we can look into this again.

**Comment by kramvan1** [comment]
On the other hand if this is doc'd as a secondary path and does not break the main chefdk path, I guess I would not mind it being there.  But we need to make it clear that any testing that fails, would need to be retried on the supported ChefDK version, before we dig deep into it.

**Comment by jjasghar** [comment]
Yeah the more i think about it; i'm ok with this. I'll let it stew for a day or two, see if i can think of any reason not to, otherwise i'll merge it.

**Comment by PierreRambaud** [comment]
ChefDK still the main target tool, but not all developers want to use it, some of them like or venerate `bundler`, same for `rvm` or `rbenv`. 
I just think it can be cool and useful to allow the utilization of many others tools,  letting other developers to choose their own way to play with this repository.

**Comment by jjasghar** [comment]
@PierreRambaud yep, agreed.

**Pull request merged**
